# Generated by Django 5.0.3 on 2024-08-11 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_userinfo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="first_name",
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="last_name",
            field=models.TextField(max_length=120),
        ),
    ]
